### ISSUE TITLE
Lab 7번 README.md

### ISSUE THREAD

**Issue by seomin3** [TeamLab/Gachon_CS50_Python_KMOOC#21]
리비전 0562d0 기준, lab 7번의 설명 중 서로 배치되는 서술이 있습니다.

README.md:
```
또한 사용자가 숫자를 정확히 입력하여 "3 Strikes" 나왔을 경우, 사용자가에게 한번 더 게임을 할 의향이 있는지 물어보고 의향이 있을 경우 다시 게임을 실행 시킵니다. 이 때 아래와 같은 조건으로 게임을 재시작을 경정합니다.

* 사용자가 이외에 입력을 하였을 경우 "Wrong Input" 이라고 출력되면서 종료된다.
```

코드 작성하여 테스트 한 결과 스크린샷과 같이 "Wrong Input, Input again" 이라고 출력되어야 하며, 다시 게임을 할 의향이 있는지 물어보도록 해야 submit됩니다.

**Comment by blissray** [comment]
감사합니다. ㅜㅜ 운영팀에어 수정해야하는 사안인데 검토해주셔서 많은도움이되었습니다.

2017. 5. 7. 오전 1:14에 "Jahyeon Koo" <notifications@github.com>님이 작성:

**Comment by blissray** [comment]
아래 Commit으로 인해, 본 이슈가 Closing 되었습니다.

https://github.com/TeamLab/Gachon_CS50_Python_KMOOC/commit/a3d3164e0db859a7eeac26815d32edd096786725#diff-cdc791c6337d5706bf60d7cbac3dea9e
